LABS-EU3/lambdaDoor_backend

- .github/pull_request_template.md
- commit_template.md
-  Add Commit , Pull request template and branch naming conventions
- https://trello.com/c/A4TJFBj1
> create commit and branch template

- .circleci/config.yml
- __tests__/sample.test.js
- package-lock.json
- package.json
Added CircleCI configuration.
https://trello.com/c/JVRT5mGc
> Setup CircleCI

- .eslintrc.json
- .prettierrc
- package-lock.json
- package.json
https://trello.com/c/veAY1Hrz/29-implement-code-style-guide
> Eslint initialization

- README.md
> Added CircleCI Badge to Readme

- api/server.js
- package-lock.json
- package.json
> Fixed bug with Eslint and Prettier

- .eslintrc.json
- __tests__/.eslintrc
- __tests__/sample.test.js
- api/server.spec.js
- package-lock.json
- package.json
- Installed Jest and Supertest
- Created and ran basic test to check GET functionality on the API
- Created an additional eslint config file to disable some rules in the tests folder to eliminate errors from requiring dev dependencies.
https://trello.com/c/iXDlgDV6
> Setup Jest and Supertest

- database/migrations/20191216141025_create-tables.js
- database/seeds/06-add-salary-reviews.js
This is to fix an error on from the seeding files which does not allow long text description. I changed the data type from varchar to text to accommodate the information
> Bug: fixed seeding error

- users/index.js
- users/userController.js
Created an endpoint on the backend to clear the 'token' cookie from the user so as to sign them out of Lambda Door.
https://trello.com/c/uKxFu8UM
> User Logout

- README.md
- knexfile.js
- package.json
- users/interests/interestsModel.js
Bug fix for interests endpoint
> Bug fix for interests

- database/migrations/20200107172153_initial.js
- database/seeds/07-add-salary-reviews.js
This chore adds an extra field in the salary table to show employee status
https://trello.com/c/aXGWDQVv/98-add-extra-field-for-employee-status-in-salary-review-table
> Chore: updated Salary Table in migration

- README.md
- companies/companyController.js
- companies/companyController.spec.js
- companies/companyModel.js
- companies/companyModel.spec.js
- companies/index.js
- userDataDisplay/dataDisplayModel.js
> Ft company with its reviews

- README.md
- companies/companyController.js
- companies/companyModel.js
- companies/index.js
Added Endpoint for adding a Company.
> Endpoint for adding a Company

- reviews/companyReviews/companyReviewsModel.js
> Bug fix for Company Review Model (Find_By_Id)

- database/seeds/02-add-companies.js
> Edited Seed file to include Company description

- reviews/interviewReviews/interviewReviewModel.js
Return company ID and user full name from GET
> Return company ID and user full name from GET

- database/migrations/20200127095749_update-interview-process-table.js
- database/seeds/06-add-interview-process-reviews.js
This PR is to update interview process table and add new columns for employee status and accepting questions
https://trello.com/c/aGGr6V25/118-accepting-more-questions-and-i-am-current-employee-for-leaving-an-interview-process-review
> Chore: updated interview process table

- README.md
- companies/companyController.js
- companies/companyModel.js
- companies/index.js
- middleware/validation.js
This PR allows only admin to make changes to the company info.
https://trello.com/c/d9a2LYS9/120-endpoint-to-edit-company-info
> Feature: edit company info

- reviews/interviewReviews/interviewReviewModel.js
Add is_accepting_questions to interview review endpoint responses
> Add is_accepting_questions to interview review endpoint responses

- README.md
- companies/companyController.js
- companies/index.js
> chore: refactored endpoint

- reviews/interviewReviews/interviewReviewController.js
Add is_accepting_questions and is_current_employee to Interview Review POST.
https://trello.com/c/6x1TNiMg
> Add is_accepting_questions and is_current_employee.

- database/migrations/20200127095749_update-interview-process-table.js
- database/migrations/20200128131220_update-interview-process-table-2.js
- database/seeds/06-add-interview-process-reviews.js
update interview table to include job role and interest ID
https://trello.com/c/Bno8gFkR/144-add-roles-to-interview-process-database-tables
> Chore: update interview table

- reviews/interviewReviews/interviewReviewModel.js
- reviews/salaryReviews/salaryReviewsModel.js
Fixed bug with interview review endpoints
> Fixed bug with interview review endpoints

- README.md
- api/server.js
- reviews/search/index.js
- reviews/search/searchController.js
- reviews/search/searchController.spec.js
- reviews/search/searchModel.js
- reviews/search/searchModel.spec.js
Backend endpoints to enable users to search for companies by location or company name, and interview and salary reviews by location, interest or job title. 
> Search endpoint

- reviews/interviewReviews/__tests__/interviewModel.test.js
- reviews/interviewReviews/__tests__/interviewReviewController.test.js
- reviews/interviewReviews/interviewReviewController.js
- reviews/interviewReviews/interviewReviewModel.js
Add Job Title and Interest to Interview Review endpoints.
> Add Job Title and Interest to Interview Review endpoints

- companies/companyModel.js
- database/seeds/03-add-interests.js
- reviews/companyReviews/companyReviewsController.spec.js
- reviews/interviewReviews/__tests__/interviewReviewController.test.js
> Ch update tests add ratings

- reviews/interviewReviews/interviewReviewModel.js
Fixed bug with interview reviews
https://trello.com/c/WdqQKpgQ
> Fixed bug with interview reviews

- companies/companyController.spec.js
- companies/companyModel.spec.js
- database/seeds/02-add-companies.js
> Ch added more tests and seeds

- reviews/interviewReviews/__tests__/interviewModel.test.js
- userDataDisplay/__test__/controller.spec.js
- users/interests/interestsController.spec.js
Added new test suites and tests to step up the coverage to about 85%
https://trello.com/c/4BlJJyii/146-write-more-tests-on-the-backend
> Chore: add more tests suites

- reviews/salaryReviews/salaryReviewsModel.js
Add user's name and is_anonymous to SR responses.
> Add user's name and is_anonymous to SR responses.

- README.md
- companies/companyController.js
- index.js
- package-lock.json
- package.json
- referrals/referralController.js
- reviews/companyReviews/companyReviewsController.js
- reviews/interviewReviews/interviewReviewController.js
- reviews/salaryReviews/salaryReviewsController.js
- reviews/search/searchController.js
- userDataDisplay/dataDisplayController.js
- users/interests/interestsController.js
- users/userController.js
> Configured Exception monitoring for the Backend

- reviews/search/searchModel.js
Added ability to search interview process reviews by company name.
> bg-fix: add company name searchability to interview process search
